---author:
---date  :
---purpose:
----the final set of the project

----TABLES
CREATE USER project2 identified by test;
GRANT DBA TO project2;

CREATE TABLE SCALES (
	SCALE  NUMERIC(2),
	BASIC_AMOUNT NUMERIC(10,3),
	HOUSING NUMERIC(3),
	TRANSPORT NUMERIC(3),
	PRIMARY KEY(SCALE)
);
CREATE TABLE dept(
      dept_id number(4,0),
      dept_name varchar2(50),     
      primary key(dept_id)
	  );
	  
CREATE TABLE  EMPLOYEE(
	EMP_ID NUMERIC(5),
	EMP_NAME VARCHAR2(50),
	DESIGNATION VARCHAR2(50),
	SCALE NUMERIC(2),
	TYPES NUMERIC(2),
	JOIN_DATE DATE,
	dept_id number(4,0),
	Taxe number(10,2),
	PRIMARY KEY(EMP_ID),
	FOREIGN KEY(SCALE) REFERENCES SCALES(SCALE),
	FOREIGN KEY(DEPT_ID) REFERENCES DEPT(DEPT_ID)
);
create table taxes (taxe_id NUMBER(2,2) primary key,
                    percentage number(3,0),
                    TYI1 number(15,2),
                    TYI2 number(15,2));

----not yet used					
CREATE TABLE administrator(
   name varchar2(50),
   password varchar2(50)
);
---insetion
INSERT INTO  SCALES VALUES(1,1000,15,5);
INSERT INTO  SCALES VALUES(2,2000,30,10);
INSERT INTO  SCALES VALUES(3,3000,40,15);
INSERT INTO  SCALES VALUES(4,4000,50,20);					


INSERT INTO  DEPT VALUES(4,'computer');
INSERT INTO dept VALUES(3,'vocation');
INSERT INTO dept VALUES(2,'electrical');
INSERT INTO dept VALUES(1,'mecanical');
INSERT INTO dept VALUES(5,'civil');
----functions
----FUNCTION FOR GENERATIING ID

CREATE OR REPLACE FUNCTION GENERATEID(DEPTID_IN NUMBER,DESIGN_IN NUMBER,TYPES_IN NUMBER)
RETURN NUMBER
IS
MAX_EMP_ID EMPLOYEE.EMP_ID%TYPE;
TEMP VARCHAR2(10);
NEW_ID VARCHAR2(10);
THE_ID EMPLOYEE.EMP_ID%TYPE;
BEGIN
NEW_ID:=CONCAT(NEW_ID,TYPES_IN);
NEW_ID:=CONCAT(NEW_ID,DEPTID_IN);
NEW_ID:=CONCAT(NEW_ID,DESIGN_IN);
SELECT MAX(EMP_ID)  INTO MAX_EMP_ID
FROM EMPLOYEE
WHERE DEPT_ID=DEPTID_IN AND TYPES=TYPES_IN;
IF MAX_EMP_ID is null THEN
NEW_ID:=CONCAT(NEW_ID,'01');
THE_ID:=TO_NUMBER(NEW_ID);
ELSE
THE_ID:=MAX_EMP_ID+1;
END IF;
RETURN THE_ID;
END;
/	
	
---
BEGIN
DBMS_OUTPUT.PUT_LINE('THE  IS: '||GENERATEID(4,1,1));
END;
/

----function to return date format
SELECT TO_DATE('2015-04-20','YY-MM-DD') FROM DUAL;
CREATE OR REPLACE FUNCTION DATEFORMAT(DATE_IN VARCHAR2)
RETURN DATE
IS
VAR_DATE DATE;
BEGIN
VAR_DATE:=TO_DATE(DATE_IN,'YY-MM-DD');
RETURN VAR_DATE;
END;
/
---CHECKING THE OUTPUT
BEGIN
DBMS_OUTPUT.PUT_LINE('THE  IS: '||DATEFORMAT('2015-04-20'));
END;
/
					




